name: payup
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: K2D
      fonts:
        - asset: assets/fonts/K2D-Thin.ttf
          weight: 100
        - asset: assets/fonts/K2D-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/K2D-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/K2D-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/K2D-Light.ttf
          weight: 300
        - asset: assets/fonts/K2D-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/K2D-Regular.ttf
          weight: 400
        - asset: assets/fonts/K2D-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/K2D-Medium.ttf
          weight: 500
        - asset: assets/fonts/K2D-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/K2D-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/K2D-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/K2D-Bold.ttf
          weight: 700
        - asset: assets/fonts/K2D-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/K2D-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/K2D-ExtraBoldItalic.ttf
          weight: 800
          style: italic
